"""init

Revision ID: 05766cf54df8
Revises: 
Create Date: 2024-07-04 14:59:41.923959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05766cf54df8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('qa_type', sa.Enum('LLM', 'RAG', 'TOOL', name='qatype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('conv_uuid', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_bases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='知识库名称'),
    sa.Column('hash_name', sa.String(length=20), nullable=False, comment='知识库哈希名称'),
    sa.Column('icon', sa.String(length=100), nullable=False, comment='知识库图标'),
    sa.Column('desc', sa.String(length=200), nullable=False, comment='知识库描述'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('group_id', sa.Integer(), nullable=True, comment='团队ID'),
    sa.Column('is_delete', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('kb_name', sa.String(length=10), nullable=False, comment='知识库名称'),
    sa.Column('file_name', sa.String(length=100), nullable=False, comment='文件名称'),
    sa.Column('file_ext', sa.String(length=10), nullable=False, comment='文件扩展名'),
    sa.Column('process_type', sa.String(length=10), nullable=True, comment='处理类型'),
    sa.Column('slice_type', sa.String(length=10), nullable=True, comment='切片类型'),
    sa.Column('weights', sa.Integer(), nullable=True, comment='权重'),
    sa.Column('meta_data', sa.JSON(), nullable=True, comment='文件元数据'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permission_association',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], )
    )
    op.create_table('user_org_role',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('file_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False, comment='文件ID'),
    sa.Column('chunk_id', sa.Integer(), nullable=False, comment='切片ID'),
    sa.Column('chunk', sa.String(length=2000), nullable=False, comment='切片文本'),
    sa.Column('chunk_uuid', sa.String(length=36), nullable=False, comment='向量UUID'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['knowledge_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_base_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False, comment='知识库ID'),
    sa.Column('search_mode', sa.String(length=20), nullable=False, comment='搜索模式'),
    sa.Column('embedding_model', sa.String(length=20), nullable=False, comment='嵌入模型'),
    sa.Column('process_type', sa.String(length=20), nullable=False, comment='处理类型'),
    sa.Column('slice_type', sa.String(length=10), nullable=False, comment='切片类型'),
    sa.Column('use_rerank', sa.Boolean(), nullable=False, comment='是否使用rerank'),
    sa.Column('max_count', sa.Integer(), nullable=False, comment='最大数量'),
    sa.Column('top_k', sa.Integer(), nullable=False, comment='topk'),
    sa.Column('advance_query', sa.Boolean(), nullable=False, comment='高级查询'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_base_configs')
    op.drop_table('file_chunks')
    op.drop_table('user_org_role')
    op.drop_table('role_permission_association')
    op.drop_table('knowledge_files')
    op.drop_table('knowledge_bases')
    op.drop_table('conversations')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('organizations')
    op.drop_table('guides')
    # ### end Alembic commands ###
