SQLALCHEMY_DATABASE_URI = "mysql+aiomysql://rag:rag#123@localhost/test?charset=utf8"

MODEL_PATH = ""

MAX_CONCURRENT_THREADS = 10

APP_SECRET_KEY = ''

REDIS_HOST='localhost' 
REDIS_PORT='6379' 
REDIS_PASSWORD='qsearch123'

ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 24 * 30
